apiVersion: v1
kind: Service
metadata:
  name: upgrade-copilot
  labels:
    app.kubernetes.io/name: upgrade-copilot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: upgrade-copilot
  ports:
    - name: http
      port: 8000
      targetPort: http
